<?php

declare(strict_types = 1);
/**
 * This file has been automatically generated by Constup Automatrix.
 * https://constup.com/automatrix
 */

namespace Constup\PharProcessor\Service\SubObject;

use Constup\Automatrix\LanguagePhp\Version0702\DesignPatternInterfaces\ValidatorInterface;

class FqnClassNameAssociationValidator implements ValidatorInterface, FqnClassNameAssociationValidatorInterface
{
    /**
     * @param string $fqn
     *
     * @return self
     */
    public function validateFqn(string $fqn): FqnClassNameAssociationValidatorInterface
    {
        return $this;
    }

    /**
     * @param string $className
     *
     * @return self
     */
    public function validateClassName(string $className): FqnClassNameAssociationValidatorInterface
    {
        return $this;
    }

    /**
     * @param FqnClassNameAssociationImmutableObjectInterface $object
     *
     * @return FqnClassNameAssociationValidatorInterface
     */
    public function validateObject(FqnClassNameAssociationImmutableObjectInterface $object): FqnClassNameAssociationValidatorInterface
    {
        return $this->validateFqn($object->getFqn())
                    ->validateClassName($object->getClassName());
    }
}
