<?php

declare(strict_types = 1);

/**
 * This file has been automatically generated by Constup Automatrix.
 * https://constup.com/automatrix
 */

namespace Constup\PharProcessor\Service\SubObject;

use Constup\Automatrix\LanguagePhp\Version0702\DesignPatternInterfaces\ValidatorInterface;

interface FqnClassNameAssociationValidatorInterface extends ValidatorInterface
{
    /**
     * @param string $fqn
     *
     * @return self
     */
    public function validateFqn(string $fqn): self;

    /**
     * @param string $className
     *
     * @return self
     */
    public function validateClassName(string $className): self;

    /**
     * @param FqnClassNameAssociationImmutableObjectInterface $object
     *
     * @return FqnClassNameAssociationValidatorInterface
     */
    public function validateObject(FqnClassNameAssociationImmutableObjectInterface $object): self;
}
