<?php

declare(strict_types = 1);
/**
 * This file has been automatically generated by Constup Automatrix.
 * https://constup.com/automatrix
 */

namespace Constup\PharProcessor\Service\SubObject;

use Constup\Automatrix\LanguagePhp\Version0702\DesignPatternInterfaces\ImmutableObjectInterface;

class FqnClassNameAssociationImmutableObject implements ImmutableObjectInterface, FqnClassNameAssociationImmutableObjectInterface
{
    /** @var string */
    private $fqn;
    /** @var string */
    private $className;

    /**
     * @param string $fqn
     * @param string $className
     */
    public function __construct(string $fqn, string $className)
    {
        $this->fqn = $fqn;
        $this->className = $className;
    }

    /**
     * @return string
     * @codeCoverageIgnore
     */
    public function getFqn(): string
    {
        return $this->fqn;
    }

    /**
     * @param string $fqn
     *
     * @return FqnClassNameAssociationImmutableObject
     */
    public function withFqn(string $fqn): FqnClassNameAssociationImmutableObjectInterface
    {
        return new self($fqn, $this->getClassName());
    }

    /**
     * @return string
     * @codeCoverageIgnore
     */
    public function getClassName(): string
    {
        return $this->className;
    }

    /**
     * @param string $className
     *
     * @return FqnClassNameAssociationImmutableObject
     */
    public function withClassName(string $className): FqnClassNameAssociationImmutableObjectInterface
    {
        return new self($this->getFqn(), $className);
    }
}
