<?php

declare(strict_types = 1);

/**
 * This file has been automatically generated by Constup Automatrix.
 * https://constup.com/automatrix
 */

namespace Constup\PharProcessor\Service\SubObject;

use Constup\Automatrix\LanguagePhp\Version0702\DesignPatternInterfaces\ImmutableObjectInterface;

interface FqnClassNameAssociationImmutableObjectInterface extends ImmutableObjectInterface
{
    /**
     * @return string
     * @codeCoverageIgnore
     */
    public function getFqn(): string;

    /**
     * @param string $fqn
     *
     * @return FqnClassNameAssociationImmutableObject
     */
    public function withFqn(string $fqn): self;

    /**
     * @return string
     * @codeCoverageIgnore
     */
    public function getClassName(): string;

    /**
     * @param string $className
     *
     * @return FqnClassNameAssociationImmutableObject
     */
    public function withClassName(string $className): self;
}
